/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoBBDD;

import conexion.Conexion;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import modelo.Cliente;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class MenuClientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public MenuClientes() {
        initComponents();
        desactivar();
        this.letraNIF.setText("J");
        this.letraNIF.setEnabled(false);
        this.totalVentas.setText("0");
        this.totalVentas.setEnabled(false);
    }

    private boolean botonAltas = false;
    private boolean botonBajas = false;
    private boolean botonModificaciones = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textocodigo = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        textoNIF = new javax.swing.JLabel();
        NIF = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        textoNombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        textoDomicilio = new javax.swing.JLabel();
        CP = new javax.swing.JTextField();
        textoCP = new javax.swing.JLabel();
        localidad = new javax.swing.JTextField();
        textoLocalidad = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JLabel();
        movil = new javax.swing.JTextField();
        textoMovil = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        textoFax = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        textoMail = new javax.swing.JLabel();
        totalVentas = new javax.swing.JTextField();
        textoVentas = new javax.swing.JLabel();
        letraNIF = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        mantenimiento = new javax.swing.JMenu();
        altas = new javax.swing.JMenuItem();
        bajas = new javax.swing.JMenuItem();
        modificaciones = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        volver = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        PC = new javax.swing.JMenu();
        listado = new javax.swing.JMenu();
        graficos = new javax.swing.JMenuItem();
        entreCodigo = new javax.swing.JMenuItem();
        porCodigo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textocodigo.setText("Codigo");

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        textoNIF.setText("N.I.F.");

        NIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIFActionPerformed(evt);
            }
        });

        textoNombre.setText("Nombre");

        textoApellidos.setText("Apellidos");

        textoDomicilio.setText("Domicilio");

        CP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPActionPerformed(evt);
            }
        });

        textoCP.setText("Codigo Postal");

        localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadActionPerformed(evt);
            }
        });

        textoLocalidad.setText("Localidad");

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        textoTelefono.setText("Telefono");

        movil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilActionPerformed(evt);
            }
        });

        textoMovil.setText("Movil");

        fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxActionPerformed(evt);
            }
        });

        textoFax.setText("Fax");

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        textoMail.setText("e-mail");

        textoVentas.setText("Total Ventas");

        letraNIF.setText("J");
        letraNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraNIFActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(75, 25));
        btnAceptar.setMinimumSize(new java.awt.Dimension(75, 25));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(81, 25));
        btnCancelar.setMinimumSize(new java.awt.Dimension(81, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(57, 25));
        btnSalir.setMinimumSize(new java.awt.Dimension(57, 25));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        mantenimiento.setText("Mantenimiento");

        altas.setText("Altas");
        altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasActionPerformed(evt);
            }
        });
        mantenimiento.add(altas);

        bajas.setText("Bajas");
        bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajasActionPerformed(evt);
            }
        });
        mantenimiento.add(bajas);

        modificaciones.setText("Modificaciones");
        modificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificacionesActionPerformed(evt);
            }
        });
        mantenimiento.add(modificaciones);
        mantenimiento.add(jSeparator1);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        mantenimiento.add(volver);

        menu.add(mantenimiento);

        consultas.setText("Consultas");

        PC.setText("Por Codigo");

        listado.setText("Listado");

        graficos.setText("Graficos");
        graficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficosActionPerformed(evt);
            }
        });
        listado.add(graficos);

        entreCodigo.setText("Entre codigos");
        entreCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreCodigoActionPerformed(evt);
            }
        });
        listado.add(entreCodigo);

        porCodigo.setText("Por Codigo");
        porCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porCodigoActionPerformed(evt);
            }
        });
        listado.add(porCodigo);

        PC.add(listado);

        consultas.add(PC);

        menu.add(consultas);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(domicilio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoApellidos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textocodigo)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoNIF)
                                        .addGap(93, 93, 93))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(NIF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letraNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoNombre)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoTelefono)
                                .addGap(64, 64, 64)
                                .addComponent(textoMovil)
                                .addGap(78, 78, 78)
                                .addComponent(textoFax))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoMail)
                                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoVentas)
                                    .addComponent(totalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textoDomicilio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoCP)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoLocalidad)
                                    .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textocodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNIF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(letraNIF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NIF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(textoApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoFax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textoTelefono)
                        .addComponent(textoMovil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoMail)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        if (!(this.codigo.getText().matches("\\d{6}"))) {
            JOptionPane.showMessageDialog(this, "El formato debe tener 6 numeros.", "Error CODIGO", JOptionPane.CLOSED_OPTION);
        }
        if (this.codigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede estar vacio.", "Error CODIGO", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_codigoActionPerformed

    private void letraNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraNIFActionPerformed
        this.letraNIF.setEnabled(false);

    }//GEN-LAST:event_letraNIFActionPerformed

    private void faxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxActionPerformed
        if (!(this.fax.getText().matches("\\d{9}")) && !(this.fax.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "El formato debe tener 9 numeros.", "Error FAX", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_faxActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        if (!(this.telefono.getText().matches("\\d{9}")) && !(this.telefono.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "El formato debe tener 9 numeros.", "Error TELEFONO", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_telefonoActionPerformed

    private void movilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilActionPerformed
        if (!(this.movil.getText().matches("\\d{9}")) && !(this.movil.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "El formato debe tener 9 numeros.", "Error MOVIL", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_movilActionPerformed

    private void CPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPActionPerformed

    private void localidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        if (!(this.mail.getText().matches("\\d{9}")) && !(this.mail.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "El e-mail tiene que tener un formato adecuado.", "Error E-MAIL", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_mailActionPerformed

    private void NIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIFActionPerformed
        if (!(this.NIF.getText().matches("\\d{8}"))) {
            JOptionPane.showMessageDialog(this, "El formato debe tener 8 numeros.", "Error NIF", JOptionPane.CLOSED_OPTION);
        }
        if (this.NIF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede estar vacio.", "Error NIF", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_NIFActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (botonAltas == true) {
            activar();
            altas();
        } else if (botonBajas == true) {
            activar();
            bajas();
        } else if (botonModificaciones == true) {
            activar();
            modificaciones();

        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    public void cosas() {
        ArrayList<Cliente> clientes = new ArrayList<>();
        Cliente cl = new Cliente();
        String codigo = this.codigo.getText();
        String nif = this.NIF.getText();
        String nombre = this.nombre.getText();
        String apellidos = this.apellidos.getText();
        String domicilio = this.domicilio.getText();
        String cp = this.CP.getText();
        String localidad = this.localidad.getText();
        String telefono = this.telefono.getText();
        String movil = this.movil.getText();
        String fax = this.fax.getText();
        String mail = this.mail.getText();
        float ventas = Float.parseFloat(this.totalVentas.getText());
        cl = new Cliente(codigo, nif, nombre, apellidos, domicilio, cp, localidad, telefono, movil, fax, mail, ventas);
        clientes.add(cl);
        despuesDeAceptar();
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        despuesDeAceptar();
        desactivar();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new Mantenimiento().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasActionPerformed
        botonAltas = true;
        botonBajas = false;
        botonModificaciones = false;
    }//GEN-LAST:event_altasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        despuesDeAceptar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void entreCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreCodigoActionPerformed
        new EntreCodigos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_entreCodigoActionPerformed

    private void bajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajasActionPerformed
        botonAltas = false;
        botonBajas = true;
        botonModificaciones = false;
    }//GEN-LAST:event_bajasActionPerformed

    private void modificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificacionesActionPerformed
        botonAltas = false;
        botonBajas = false;
        botonModificaciones = true;
    }//GEN-LAST:event_modificacionesActionPerformed

    private void graficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graficosActionPerformed

    private void porCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porCodigoActionPerformed
        activar();
    }//GEN-LAST:event_porCodigoActionPerformed

    public void altas() {
        try {
            Cliente cl = new Cliente();
            Conexion conn = new Conexion();
            String sql = """
                         INSERT INTO clientes(codigo, nif, apellidos, nombre, domicilio, codigoPostal, localidad, telefono, movil, fax, mail, totalVentas)
                         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                         """;
            PreparedStatement ps = (conn.Conexion()).prepareStatement(sql);

            ps.setString(1, cl.getCodigo());
            ps.setString(2, cl.getNif());
            ps.setString(3, cl.getApellidos());
            ps.setString(4, cl.getNombre());
            ps.setString(5, cl.getDomicilio());
            ps.setString(6, cl.getCodigo_postal());
            ps.setString(7, cl.getLocalidad());
            ps.setString(8, cl.getTelefono());
            ps.setString(9, cl.getMovil());
            ps.setString(10, cl.getFax());
            ps.setString(11, cl.getMail());
            ps.setFloat(12, cl.getTotal_ventas());

            ps.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(MenuClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void bajas() {

    }

    public void modificaciones() {

    }

    public void buscarPorCodigo() {
        try {
            Conexion conn = new Conexion();
            String sql = """
                         SELECT codigo, nif, apellidos, nombre, domicilio, codigoPostal, localidad, telefono, movil, fax, mail, totalVentas
                         FROM clientes
                         WHERE codigo = ?
                         """;
            //TODO
            PreparedStatement ps = (conn.Conexion()).prepareStatement(sql);

            ps.setString(1, sql);

            ps.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(MenuClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void eliminar() {
        try {
            Conexion conn = new Conexion();
            String sql = """
                         DELETE FROM clientes
                         WHERE codigo = ?
                         """;

            //TODO
            PreparedStatement ps = (conn.Conexion()).prepareStatement(sql);

            ps.setString(1, sql);

            ps.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(MenuClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void update() {
        try {
            Conexion conn = new Conexion();
            String sql = """
                         UPDATE clientes SET
                         apellidos = ?,
                         nombre = ?,
                         domicilio = ?,
                         codigoPostal = ?,
                         localidad = ?,
                         telefono = ?,
                         movil = ?,
                         fax = ?,
                         mail = ?
                         WHERE codigo = ?
                         """;

            //TODO
            PreparedStatement ps = (conn.Conexion()).prepareStatement(sql);

            ps.setString(1, sql);
            ps.setString(2, sql);
            ps.setString(3, sql);
            ps.setString(4, sql);
            ps.setString(5, sql);
            ps.setString(6, sql);
            ps.setString(7, sql);
            ps.setString(8, sql);
            ps.setString(9, sql);
            ps.setString(10, sql);

            ps.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(MenuClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void despuesDeAceptar() {
        this.codigo.setText("");
        this.NIF.setText("");
        this.nombre.setText("");
        this.apellidos.setText("");
        this.domicilio.setText("");
        this.CP.setText("");
        this.localidad.setText("");
        this.telefono.setText("");
        this.movil.setText("");
        this.fax.setText("");
        this.mail.setText("");
        this.totalVentas.setText("");
        this.codigo.grabFocus();
    }

    public void desactivar() {
        this.codigo.setEnabled(false);
        this.NIF.setEnabled(false);
        this.nombre.setEnabled(false);
        this.apellidos.setEnabled(false);
        this.domicilio.setEnabled(false);
        this.CP.setEnabled(false);
        this.localidad.setEnabled(false);
        this.telefono.setEnabled(false);
        this.movil.setEnabled(false);
        this.fax.setEnabled(false);
        this.mail.setEnabled(false);
        this.codigo.setEnabled(false);
        this.btnAceptar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnSalir.setEnabled(false);
    }

    private void activar() {
        this.codigo.setEnabled(true);
        this.NIF.setEnabled(true);
        this.nombre.setEnabled(true);
        this.apellidos.setEnabled(true);
        this.domicilio.setEnabled(true);
        this.CP.setEnabled(true);
        this.localidad.setEnabled(true);
        this.telefono.setEnabled(true);
        this.movil.setEnabled(true);
        this.fax.setEnabled(true);
        this.mail.setEnabled(true);
        this.btnAceptar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.btnSalir.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CP;
    private javax.swing.JTextField NIF;
    private javax.swing.JMenu PC;
    private javax.swing.JMenuItem altas;
    private javax.swing.JTextField apellidos;
    private javax.swing.JMenuItem bajas;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField codigo;
    private javax.swing.JMenu consultas;
    private javax.swing.JTextField domicilio;
    private javax.swing.JMenuItem entreCodigo;
    private javax.swing.JTextField fax;
    private javax.swing.JMenuItem graficos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField letraNIF;
    private javax.swing.JMenu listado;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField mail;
    private javax.swing.JMenu mantenimiento;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem modificaciones;
    private javax.swing.JTextField movil;
    private javax.swing.JTextField nombre;
    private javax.swing.JMenuItem porCodigo;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoCP;
    private javax.swing.JLabel textoDomicilio;
    private javax.swing.JLabel textoFax;
    private javax.swing.JLabel textoLocalidad;
    private javax.swing.JLabel textoMail;
    private javax.swing.JLabel textoMovil;
    private javax.swing.JLabel textoNIF;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoTelefono;
    private javax.swing.JLabel textoVentas;
    private javax.swing.JLabel textocodigo;
    private javax.swing.JTextField totalVentas;
    private javax.swing.JMenuItem volver;
    // End of variables declaration//GEN-END:variables
}
